---
name: workflow
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v2.0.3
  push:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    - uses: google-github-actions/deploy-cloud-functions@v0
      with:
        event_trigger_resource: projects/_/buckets/wowless.dev
        event_trigger_service: storage.googleapis.com
        event_trigger_type: google.storage.object.finalize
        name: genindex
        runtime: python39
        service_account_email: genindex-runner@www-wowless-dev.iam.gserviceaccount.com
